{{- if eq .Values.mode "standalone" }}
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "storvia.fullname" . }}
  labels:
    app: {{ template "storvia.name" . }}
    chart: {{ template "storvia.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.persistence.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.persistence.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.volumeName }}
  volumeName: "{{ .Values.persistence.volumeName }}"
  {{- end }}
  {{- include "storvia.persistence.storageClass" ( dict "persistence" .Values.persistence "global" .Values.global) | nindent 2 }}
{{- end }}
{{- end }}
