apiVersion: v1
description: High Performance Object Storage
name: minio
version: 5.5.0
appVersion: RELEASE.2024-12-18T13-15-44Z
keywords:
  - minio
  - storage
  - object-storage
  - s3
  - cluster
home: https://github.com/ergin84/minio
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/ergin84/minio
maintainers:
- name: ergin84
  email: erginmehmeti@gmail.com
